<?php

namespace Tests\Feature\Http\Controllers;

use App\Http\Middleware\VerifyCsrfToken;
use App\Models\Label;
use App\Models\Task;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class LabelControllerTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutMiddleware(VerifyCsrfToken::class);
        DB::beginTransaction();
    }

    public function testLabelIndex(): void
    {
        $response = $this->get(route('labels.index'));
        $response->assertOk();
    }

    public function testCreateWithoutAutorize()
    {
        $response = $this->get(route('labels.create'));
        $response->assertStatus(302);
        $response->assertRedirect(route('login'));
        $this->assertGuest();
    }

    public function testCreateWithAutorize()
    {
        $user = User::factory()->create();
        $response = $this->actingAs($user)
            ->get(route('labels.create'));
        $response->assertOk();
    }

    public function testStoreWithoutAutorize()
    {
        $label = Label::factory()->make();
        $response = $this->post(route('labels.store'), $label->toArray());
        $response->assertRedirect(route('login'));
        $response->assertStatus(302);
    }

    public function testStoreWithAutorize()
    {
        $user = User::factory()->create();
        $label = Label::factory()->make()->toArray();
        $response = $this->actingAs($user)
            ->post(route('labels.store'), $label);
        $response->assertSessionHasNoErrors();
        $response->assertRedirect(route('labels.index'));
        $response->assertStatus(302);
        $this->assertDatabaseHas('labels', $label);
    }

    public function testEditWithoutAutorize()
    {
        $label = Label::factory()->create();
        $response = $this->get(route('labels.edit', $label));
        $response->assertStatus(302);
        $response->assertRedirect(route('login'));
        $this->assertGuest();
    }

    public function testEditWithAuthUser()
    {
        $user = User::factory()->create();
        $label = Label::factory()->create();
        $response = $this->actingAs($user)
            ->get(route('labels.edit', $label));
        $response->assertOk();
    }

    public function testDeleteWithoutAutorize()
    {
        $label = Label::factory()->create();
        $response = $this->delete(route('labels.destroy', $label));
        $response->assertStatus(302);
        $response->assertRedirect(route('login'));
        $this->assertGuest();
    }

    public function testDeleteWithAuthUser()
    {
        $user = User::factory()->create();
        $label = Label::factory()->create();
        $response = $this->actingAs($user)
            ->delete(route('labels.destroy', $label));
        $response->assertSessionHasNoErrors();
        $response->assertRedirect(route('labels.index'));
        $response->assertStatus(302);
        $this->assertDatabaseMissing('labels', $label->toArray());
    }

    protected function tearDown(): void
    {
        DB::rollBack();
        parent::tearDown();
    }
}
